### ISSUE TITLE
Check for one letter variables

### ISSUE THREAD

**Issue by gforcada** [plone/plone.recipe.codeanalysis#100]
As @jensens pointed out in https://github.com/plone/plone.api/issues/188, a one-letter variable is not only bad when interacting with debuggers but also a really harmful bad practice, as it hinders the purpose of putting a name to an expression: to know what's holding and what's the expected use.

**Comment by do3cc** [comment]
This could be used as a base: https://github.com/PyCQA/pep8-naming
Still without single letter check though

**Comment by gforcada** [comment]
Indeed, a flake8 plugin might be much better than adding it here
