### ISSUE TITLE
Replace manual written linters with flake8 plugins

### ISSUE THREAD

**Issue by saily** [plone/plone.recipe.codeanalysis#112]
While refactoring in #109 i thought about removing this manual checks and replace them with some currently available flake8 plugins. See:
http://pythoncodereview.com/flake8-plugins.html

pros:
- we don't have to maintain, test and fix them

cons:
- limited to Python
- maybe they will not fit our guidelines
- API change (again)

What do you think?

**Comment by saily** [comment]
suggested addons:

      install_requires=[
          'flake8',
          'flake8-quotes',
          # 'flake8-docstrings',
          'flake8-debugger',
          'flake8-print',
          'flake8-blind-except',
          'pep8-naming',
          'setuptools',
          'zc.buildout',
          'zc.recipe.egg',
      ],

`flake8-docstrings` is too verbose for me, but all others work fine. You may also ignore them by adding the ErrorCode to `flake8-ignore`.

**Comment by gforcada** [comment]
:+1: as long as the current behavior is kept.

Actually I had some early prototypes to move our linters to be flake8 plugins, should we aim for that (I'm :+1: on this)

**Comment by tisto** [comment]
+1

**Comment by hvelarde** [comment]
:+1: for the following:
* flake8-docstrings (this has been requested before in #59)
* flake8-blind-except
* flake8-debugger (need to find a way to disallow debugger on JS code)
* flake8-quotes

:+1: for the following:
* pep8-naming (we have a bunch of legacy code that will need to be skipped)
* flake8-import-order (our convention is different than the one on PEP 8)

we can remove a bunch of stuff from our package with this.

this could be the time for a clean up of the API and removal of all unsupported options: 2.0a1?

@gforcada :+1: also on making some of our code flake8 plugins.
