### ISSUE TITLE
Check for plone.api usages

### ISSUE THREAD

**Issue by gforcada** [plone/plone.recipe.codeanalysis#118]
An idea from @datakurre: provide a check that warns about usages that could be replaced by plone.api (i.e. getToolByName and other things like that)

**Comment by saily** [comment]
We could already implement this using the existing `deprecated_aliases` script. 
Wouldn't it be great if we maintain or retrieve an `xml` or `json` file with those information, which is stored in `plone.api` so that we always retrieve the correct **replacements** file from the used version of `plone.api`?

**Comment by gforcada** [comment]
That would be a great idea indeed!

Moving over to plone.api then :)

**Comment by jaroel** [comment]
We cannot do this in the plone.api dependencies, so this should be warnings.

**Comment by rodfersou** [comment]
:+1: Great idea

**Comment by hvelarde** [comment]
why not add deprecation warning on Plone core code itself?

**Comment by jaroel** [comment]
Because we're not changing Plone core to plone.api, and plone.api uses that 'old' code :)

**Comment by saily** [comment]
you need to increase your scrollback buffer if you run code-analysis on the plone core with deprecation warning :-)

**Comment by hvelarde** [comment]
@jaroel you're right.

@saily I'm against using the existing ``deprecated_aliases`` because we are talking about different checks here; technically the script must be the same, but we have to add another option for it.

**Comment by saily** [comment]
@hvelarde do you have a suggestion for a new naming/attribute/option?

**Comment by hvelarde** [comment]
I'm really bad at naming things: ``enforce-plone-api-usage``?

**Comment by rodfersou** [comment]
how about `best_practices_advise` as name

**Comment by tisto** [comment]
@rodfersou my feeling is that "best_practice_advise" is too generic. Maybe "check-plone-api-usage"?

**Comment by rodfersou** [comment]
@tisto sounds good

**Comment by gforcada** [comment]
On the meantime I made this: https://pypi.python.org/pypi/flake8-plone-api consider it totally **alpha** I just made up the replacements by looking at which (weird) methods where being used on the implementation of each plone.api method.

Pull requests welcome!
