### ISSUE TITLE
New milestone: plone best practices

### ISSUE THREAD

**Issue by gforcada** [plone/plone.recipe.codeanalysis#119]
One could say that versions 0.x and 1.x were mostly about adding code analysis facilities.

2.0 is about refactoring to make the code more maintainable and extendable.

So the next step, for me at least, would it be to add linters to enforce plone testing/coding/docs best practices (check for plone.api usage, documentation, testing best practices...)

Any ideas/opinions on what should we focus on next?

**Comment by saily** [comment]
Feel free to add issues and add them to *3.0 - Plone best practices* milestone.
