### ISSUE TITLE
More checks: readme

### ISSUE THREAD

**Issue by gforcada** [plone/plone.recipe.codeanalysis#121]
https://pypi.python.org/pypi/readme

As it seems to be the one going to be used for the future version of PyPI it makes _a lot_ of sense to support it.

**Comment by tisto** [comment]
+1 Would be great to have that feature, especially for Plone core packages.

**Comment by tisto** [comment]
I just made a 3.0.0 release with a broken pypi readme: https://pypi.org/project/plone.recipe.codeanalysis/3.0.0/

We should really re-visit this and make it part of our checks. zest.releaser can ship with "readme", though it seems it does not run this command by default. @mauritsvanrees can you help here?

**Comment by mauritsvanrees** [comment]
I would like that. But such an automated check has been on the wish list in zest.releaser for a couple of years, so don't hold your breath. See https://github.com/zestsoftware/zest.releaser/issues/112.

**Comment by gforcada** [comment]
I guess this is no longer the place to add this, a github action, pre-commit hook, or plain integration of tooling is best nowadays 😄
