### ISSUE TITLE
Use zope.testing to check log output.

### ISSUE THREAD

**Issue by tisto** [plone/plone.recipe.codeanalysis#122]
zope.testing allows to check the log output:

https://pypi.python.org/pypi/zope.testing#support-for-testing-logging-code

It might make sense to use this in our tests to clean up our test output.

**Comment by gforcada** [comment]
Here's a WIP attempt at fixing this: https://github.com/plone/plone.recipe.codeanalysis/tree/clean-output-on-tests-122

Although a bit tricky: ``zope.testing`` is able to scan loggers created vi python ``import logging``, but we are doing ``print()``.

I was playing with it some weeks/months ago, if anyone feels up to it, please be my guest.

**Comment by hvelarde** [comment]
probably is easier to use the [textfixtures](https://pypi.python.org/pypi/testfixtures) module; I was working with it in [collective.fingerpointing](https://github.com/collective/collective.fingerpointing/blob/master/src/collective/fingerpointing/tests/test_registry_subscriber.py#L21:L27) and is really easy.

**Comment by hvelarde** [comment]
probably is easier to use the [textfixtures](https://pypi.python.org/pypi/testfixtures) module; I was working with it in [collective.fingerpointing](https://github.com/collective/collective.fingerpointing/blob/master/src/collective/fingerpointing/tests/test_registry_subscriber.py#L21:L27) to test logs and is really easy.

It supports [testing output to streams](https://pythonhosted.org/testfixtures/streams.html) also.
