### ISSUE TITLE
Create hooks folder if it doesn't exist

### ISSUE THREAD

**Issue by gforcada** [plone/plone.recipe.codeanalysis#124]
Right now to add the commit hook it is checked if '.git/hooks' folder exist and if not it errors out.

For whichever reason I got some git repositories which didn't have the hooks folder but were indeed git repositories.

So maybe we could first check if the .git folder exists and if not error as right now, but if it does exist, let's just create the hooks folder.

Does that sound sane?

**Comment by tisto** [comment]
Yes. +1
