### ISSUE TITLE
noqa no effect on multiline

### ISSUE THREAD

**Issue by jensens** [plone/plone.recipe.codeanalysis#126]
in a test i have a::

    def testfunc(): pass  # noqa

which is still reported as *E701 multiple statements on one line (colon)*

**Comment by gforcada** [comment]
Which code analysis is showing that? I guess flake8? Then is nothing we can do from p.r.codeanalysis and should be reported on flake8 itself.

If it's on one of our analyzers, then sure, we can fix it :) which one though?

**Comment by jensens** [comment]
yes, flake8

**Comment by saily** [comment]
Add a `flake8-ignore=E701`.
