### ISSUE TITLE
imports-exclude don't work properly with zc.buildout = 1.7.1

### ISSUE THREAD

**Issue by gil-cano** [plone/plone.recipe.codeanalysis#129]
In a package with many wrong imports, when excluding more than one directory with something like:

```xml
imports-exclude =
    ${:directory}/browser
    ${:directory}/content
```
zc.buildout 1.7.1 puts the next element in bin/code-analysis script

```
{... 'imports-exclude': '\n/Users/plone/matem.solicitudes/src/matem/solicitudes/browser\n/Users/plone/matem.solicitudes/src/matem/solicitudes/content' ...}
```
Which *split_lines* method in *analyser.py* transform into the list
```
['', '/Users/plone/matem.solicitudes/src/matem/solicitudes/browser', '/Users/plone/matem.solicitudes/src/matem/solicitudes/content']
```
It looks like the fist element is excluding every directory, as it finish with

```xml
Check imports........................[ OK ]
```

**Comment by gforcada** [comment]
As you show, *split_lines* creates a list of **3** elements, the first one being an empty string, which basically, I guess, makes it ignore everything.

*split_lines* should be improved to not create such an element. Pull requests welcome ;)
