### ISSUE TITLE
Allow to define directory to check via command line argument

### ISSUE THREAD

**Issue by frisi** [plone/plone.recipe.codeanalysis#135]
currently this recipe only allows to define the directory to check via an option in the buildout configuration:

```
[code-analysis]
recipe = plone.recipe.codeanalysis
directory =  ${buildout:directory}/src
imports = True
```

when working on customer projects i usually have several packages under the src directory.
customer.theme, customer.site, and several collective.* and Products.* packages i need to extend/adapt.
before touching these packages, one should run code-analysis and fix errors - if any.
to not get overwhelmed by errors of all the other packages currently in src/ folder on currently needs to define  a separate part for code analysis for this package:

```
[code-analysis-somepackage]
<= code-analysis
directory =  ${buildout:directory}/src/some.package
```

it would be a nice feature to allow to limit the directory given in the buildout part further via a command line argument
`bin/code-analyisis -d some.package` or `bin/code-analysis -d src/some.package`

**Comment by hvelarde** [comment]
+1 on this; I've been thinking… can't we just read this information somehow using the pkg_resources module?

**Comment by tisto** [comment]
+1
