### ISSUE TITLE
Integrate isort

### ISSUE THREAD

**Issue by gforcada** [plone/plone.recipe.codeanalysis#148]
Finally my [pull request](https://github.com/timothycrosley/isort/pull/294) on [isort](https://github.com/timothycrosley/isort) got merged and [released (4.1.0)](https://pypi.python.org/pypi/isort).

Which basically means that upon integrating isort on p.r.codeanalysis we can drop our own import checker and use isort for it, which on top of that, not only sorts the way plone.api describes but can do both reporting only (for CI and commit hook integration) as well as automatically fixing all imports.

I will try to do it, but please beat me on that!

**Comment by tisto** [comment]
AWESOME!!! Can't wait to see that in p.r.codeanalysis! :)

**Comment by saily** [comment]
I'll check this and already put it on my todo list, great!

**Comment by saily** [comment]
@tisto @gforcada do you prefer to have an `isort.cfg` file or using the same approach we use for `flake8-option`. I would suggest we support both, but which should be default?

**Comment by gforcada** [comment]
@saily ``isort`` itself already checks for ``isort.cfg`` I guess... but concerning p.r.codeanalysis, I would ignore it completely, let's keep everything on a buildout part definition.
