### ISSUE TITLE
zest.releaser plugin

### ISSUE THREAD

**Issue by gforcada** [plone/plone.recipe.codeanalysis#154]
I think it makes a lot of sense to create a plugin for [zest.releaser](https://pypi.python.org/pypi/zest.releaser).

A **prerelease** one I would say, so before releasing you get the chance to see the _awesome/sorry_ state of your distribution.

**Comment by do3cc** [comment]
A plugin that adds/updates the zest.releaser status in the readme

**Comment by gforcada** [comment]
@do3cc what's a zest.releaser status in the readme? You mean the version (post1, dev, stable), trove classifiers? I'm lost sorry.

**Comment by do3cc** [comment]
Sorry, I wasn't clear with my idea.

My suggestion is that zest.releaser could put the state of the distribution into the readme.
It already updates the readme to change the version, it could also add a quality report.

**Comment by gforcada** [comment]
Oh I see, nice idea yes.
