### ISSUE TITLE
Accessibility checks

### ISSUE THREAD

**Issue by gforcada** [plone/plone.recipe.codeanalysis#155]
It would be cool if templates could be checked for potential accessibility errors.

@polyester is there any library for that? If possible without involving a browser?

**Comment by polyester** [comment]
I'm not aware there's a tool that checks individual templates. There's https://addyosmani.github.io/a11y that checks against URL's, which could possibly be run as part of acceptance/install test, but individual templates would be hard I think.

**Comment by gforcada** [comment]
Yeah seems like.

I found this http://blog.pivotal.io/labs/labs/accessibility-testing-javascript which lists a few options (I guess not for template-based but URL based):
- https://github.com/squizlabs/HTML_CodeSniffer
- https://github.com/GoogleChrome/accessibility-developer-tools (Chrome extension)
- https://github.com/quailjs/quail

I also found this, which seems interesting as well: http://pa11y.org/

Noting them here as a later reference whenever I have time to look at it again.

**Comment by polyester** [comment]
quailjs is great, but is for content. We should really try to bundle that with TinyMCE, but my grunt-fu is limited.

**Comment by gforcada** [comment]
@polyester as I understood it, if we create enough dummy content and then fire phantomjs we could check the accessibility status of those pages right? and if we run that on CI it would mean we could pin point where accessibility problems where introduced.

**Comment by gforcada** [comment]
I guess this is no longer the place to add this, a github action, pre-commit hook, or plain integration of tooling is best nowadays 😄
