### ISSUE TITLE
AttributeError: 'ModuleScope' object has no attribute 'returnValue'

### ISSUE THREAD

**Issue by khink** [plone/plone.recipe.codeanalysis#165]
Hi,

First off i really like this recipe, and wanted to use it in Products.LoginLockout.

I ran into the problem where a skins folder script has a bare return statement, and pyflakes < 0.9.0 throws an exception: "AttributeError: 'ModuleScope' object has no attribute 'returnValue'" . As the current flake8 (2.4.1) is still pinning to < 0.9.0, this is a problem. https://bugs.launchpad.net/pyflakes/+bug/1332451

How could we work around this? I'm currently adding the offending files to ``flake8-exclude``.

**Comment by gforcada** [comment]
As discussed briefly at the conference: the syntax error is valid, there is a return statement without being in a scope (method, class, function...).

As skins templates anyway are already special I usually put them on the exclude list.

More of a reason to get rid of them as soon as possible :-)

Feel free to close if you think so.

**Comment by khink** [comment]
As this is not the recipe's problem, it's fair to close it i think.
