### ISSUE TITLE
Check for git specific configurations

### ISSUE THREAD

**Issue by gforcada** [plone/plone.recipe.codeanalysis#166]
That's a broad way to say implement this RFC: https://github.com/plone/Products.CMFPlone/issues/1198

We could make it a bit broader though (optional then probably) to check other things, nothing pops up in my mind right now though.

Question is if we want to put that in plone.recipe.codeanlysis source tree or use it as an external library (_a la_ flake8 plugins).

The more I worked with the flake8 plugins the more I think it make sense to go on that direction, but no strong feelings for either side.

**Comment by do3cc** [comment]
This plugin implements this: https://github.com/mgedmin/check-manifest

**Comment by gforcada** [comment]
I guess this is no longer the place to add this, a github action, pre-commit hook, or plain integration of tooling is best nowadays 😄
