### ISSUE TITLE
Broken tests

### ISSUE THREAD

**Issue by gforcada** [plone/plone.recipe.codeanalysis#167]
Travis is failing on master: https://travis-ci.org/plone/plone.recipe.codeanalysis/jobs/90321940

Seems that the last release of flake8-quotes broke it (?).

On one hand we are testing on test_flake8.py code that is not within p.r.codeanalysis but instead on flake8 plugins (flake8-quotes just being one of them).

On the other hand we are not pinning a version thus being exposed to these kind of failures.

I would say that we have to do both:
- pin versions and bump them on a pull request to ensure master is always green
- (re)move the tests on p.r.codeanalysis and put them on the upstream flake8 plugins, and fix the issues there

Opinions?

**Comment by gforcada** [comment]
Pinning everything seems to not be enough: https://github.com/plone/plone.recipe.codeanalysis/pull/168

**Comment by tisto** [comment]
Sounds good. +1

**Comment by gforcada** [comment]
Both things done!
