### ISSUE TITLE
IOError while using flake8-quotes extension

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.recipe.codeanalysis#182]
barely related with plone.recipe.codeanalysis; have anybody seen an error like this before?

```python
IOError: [Errno 2] No such file or directory: '/home/travis/build/collective/collective.fingerpointing/eggs/flake8_quotes-0.2.3-py2.7.egg/VERSION'
```

full traceback here: https://travis-ci.org/collective/collective.fingerpointing/jobs/110178247#L1244

**Comment by gforcada** [comment]
never seen it, would be more useful to report it upstream though: https://github.com/zheller/flake8-quotes I see that the error is on version 0.2.3 which seems to be just released, so big chances that is due to that (?)

**Comment by hvelarde** [comment]
thanks!

**Comment by mauritsvanrees** [comment]
It's this recent change:
https://github.com/zheller/flake8-quotes/commit/790ffd02ecdcbc62ffb35315c7f77042b5c149b1
Looks like the VERSION file is included fine in the distribution, but it does not end up at the correct place in the installed package.

**Comment by do3cc** [comment]
I had to pin my projects to 0.1.2 there it works. 0.2.2 was also broken. The maintainers lack a bit of packaging knowledge.
The PR is alraedy done but nobody merged it yet.

**Comment by hvelarde** [comment]
I noticed he is not very interested on the project.

**Comment by do3cc** [comment]
My pain level has reached 80% to be willing to fork it :-)
