### ISSUE TITLE
<img tal:replace .... doesn't need an i18n:attributes

### ISSUE THREAD

**Issue by agitator** [plone/plone.recipe.codeanalysis#188]
```
...some_template.pt:59:18:
-ERROR- - alt attribute of <img> lacks i18n:attributes
-------------------------------------------------------------------------------
```

the replace should be considered somehow

**Comment by do3cc** [comment]
Please more context.
I just guess, but your image tag has a tal:replace?
If so, is the replacement not an image tag? Does it have an alt tag? How shall the i18n:extractor know about this? Maybe you might actually want to add the tag after all?

**Comment by gforcada** [comment]
@agitator a newer version of i18ndude already fixed that, if you search on its issue tracker or CHANGES.rst you will find it.

**Comment by agitator** [comment]
the precommit hook was ranting about it and yes it was an image tag that got replaced

the issue i found https://github.com/collective/i18ndude/issues/4 is from 2013?
the i18ndude within that buildout is 4.0.1

... will test again

**Comment by gforcada** [comment]
@agitator yes, thanks for digging it out, wow 2013! time flies...

**Comment by agitator** [comment]
4.0.1 solves that
