### ISSUE TITLE
Add support for bandit?

### ISSUE THREAD

**Issue by gforcada** [plone/plone.recipe.codeanalysis#194]
https://pypi.python.org/pypi/bandit

**Comment by hvelarde** [comment]
seems to be useful in a couple of situations as long as we prepare a profile for Plone projects; for instance, using `assert` in code should not make the code analysis fail.

**Comment by gforcada** [comment]
I guess this is no longer the place to add this, a github action, pre-commit hook, or plain integration of tooling is best nowadays 😄
