### ISSUE TITLE
_code_analysis_prefer_single_quotes_lines_parser method is too complex.

### ISSUE THREAD

**Issue by tisto** [plone/plone.recipe.codeanalysis#26]
Flake8 max complexity complains about this method:

/home/timo/workspace/krebswegweiser/src/plone.recipe.codeanalysis/plone/recipe/codeanalysis/__init__.py:451:1: C901 '_code_analysis_prefer_single_quotes_lines_parser' is too complex (10)

**Comment by gforcada** [comment]
According to @saily this can be closed as #109 got merged.
