### ISSUE TITLE
test for relative imports

### ISSUE THREAD

**Issue by pbauer** [plone/plone.recipe.codeanalysis#44]
like:

    from .. import messageFactory

or

    from .utils import supermethod

**Comment by gforcada** [comment]
+1 also for me, keep the full path everywhere and refactorings and code checks will be much much easier

**Comment by hvelarde** [comment]
and soon you'll find yourself with things like this:

https://github.com/plone/plone.app.contenttypes/blob/master/plone/app/contenttypes/tests/test_behaviors_collection.py#L9

or, worst, like this:

https://github.com/plone/plone.app.contenttypes/blob/master/plone/app/contenttypes/tests/test_behaviors_richtext.py#L12

when you also want to enforce the 80 char limit on lines.

**Comment by do3cc** [comment]
I usually don't spend a lot of time reading import lines to understand code.
Sorting becomes trickier though

**Comment by tisto** [comment]
@hvelarde I agree that long imports are a problem. Though, a "#noqa" might be a good solution in that case (which would also solve the sorting problem). Relative imports cause far more problems than they would possibly solve in my opinion though.

**Comment by hvelarde** [comment]
@tisto I agree

**Comment by do3cc** [comment]
Sounds like a good compromise

**Comment by gforcada** [comment]
I don't see much of a problem with wrapping import lines, as you usually don't bother looking at them that much anyway.

For me, relative imports problem is more about being able to found those imports to do QA on them.
