### ISSUE TITLE
Document csslint options.

### ISSUE THREAD

**Issue by ramiroluz** [plone/plone.recipe.codeanalysis#56]
Document the csslint options that are shown in the example. 

--format=compact
--quiet
--ignore=adjoining-classes,floats,font-faces,font-sizes,ids,qualified-headings,unique-headings
--exclude-list=foo/bar/static/third-party.css

**Comment by saily** [comment]
is this really necessary? from my point of view a link to CSSLint documentation should be enough, @hvelarde i agree.

**Comment by gforcada** [comment]
:+1: on just a link, we don't want to duplicate documentation that we will never keep up to date...
