### ISSUE TITLE
Using "--format=compact" in a .csslintrc breaks the config

### ISSUE THREAD

**Issue by tisto** [plone/plone.recipe.codeanalysis#58]
Steps to reproduce (with latest master from github):

1) Create a .csslintrc with:

--exclude-list=bootstrap.css
--quiet
--ignore=adjoining-classes,floats,font-faces,font-sizes,ids,qualified-headings,unique-headings

2) Run code-analysis-csslint

3) Add "--format=compact" to the conf above

4) Run code-analysis-csslint and it will ignore all the settings in your .csslintrc

--format=compac

**Comment by saily** [comment]
as @hvelarde already wrote this issue is invalid. cannot reproduce at all. working fine with `--format=compact`.
