### ISSUE TITLE
Add a rst linter

### ISSUE THREAD

**Issue by gforcada** [plone/plone.recipe.codeanalysis#64]
Maybe is a bit tangential to plone.recipe.codeanalysis, as it's not about checking code but rather documentation...

Still everyone these days (in Plone at least) is using reStructuredText to format documentation, so a linter for it would be really helpful to have it here.

I'm sure there have to be more, but I found this one which looks promising:

https://pypi.python.org/pypi/restructuredtext_lint

**Comment by tisto** [comment]
I added a rest check to bobtemplates plone:

https://github.com/plone/bobtemplates.plone/pull/65/files

I guess we should add this to both p.r.codeanalysis and zest.releaser. cc @mauritsvanrees (and thanks for your help).

**Comment by do3cc** [comment]
I believe the pypa has a tool that can be used: https://github.com/pypa/readme_renderer
In the end it also calls the distutils checker

**Comment by gforcada** [comment]
I guess this is no longer the place to add this, a github action, pre-commit hook, or plain integration of tooling is best nowadays 😄
