### ISSUE TITLE
jscs check takes ages

### ISSUE THREAD

**Issue by tisto** [plone/plone.recipe.codeanalysis#81]
I'm not sure if this is just that jscs takes so long for checks or if we are doing something wrong in p.r.codeanalysis. In comparison to flake8 or jshint, jscs take ages. Instead of one second the check takes 10 seconds or longer on a project with just a couple of js files.

@saily @garbas Do you have a similar experience or am I doing something wrong?

**Comment by saily** [comment]
Closed through #110
