### ISSUE TITLE
Integrate flake8 ``hacking`` extensions

### ISSUE THREAD

**Issue by gforcada** [plone/plone.recipe.codeanalysis#86]
See https://pypi.python.org/pypi/hacking for details, the TLDR is: ``hacking`` is a set of extensions to flake8.

There are quite a few interesting plugins/checks.

Documentation for ``hacking``: http://docs.openstack.org/developer/hacking/

**Comment by saily** [comment]
@gforcada can we close this?

**Comment by gforcada** [comment]
@saily I just tried adding it on ``flake8-extensions`` but it's giving dependency problems, needs older version of flake8 and so on... so we either decide to not use it at all, or we have to integrate it differently.

Feel free to close it if you feel like so.

**Comment by tisto** [comment]
@gforcada I think the flake8 problem is unrelated. The latest flake8 release introduced some version pins that break stuff: https://pypi.python.org/pypi/flake8 (pin to flake8 2.3.0 to fix).

**Comment by saily** [comment]
just wanted to post, i already tried ``hacking`` and it's possible to use in ``flake8-extensions`` when pinning ``flake8==2.2.4``.

**Comment by saily** [comment]
So from my point of view, this is now implemented and it's up to your own to use it.
