### ISSUE TITLE
Add spell checker to sphinx

### ISSUE THREAD

**Issue by gforcada** [plone/plone.recipe.codeanalysis#87]
That and a linter for rst files would be massively beneficial, not only for code and tests, but also for documentation too :)

This extension implements it: 
https://bitbucket.org/dhellmann/sphinxcontrib-spelling/overview

**Comment by do3cc** [comment]
Do you keep in mind that the readme files should NOT use sphinx extensions?
They aren't understood by pypi.

**Comment by gforcada** [comment]
I guess this is no longer the place to add this, a github action, pre-commit hook, or plain integration of tooling is best nowadays 😄
