### ISSUE TITLE
Prefer single quotes don't respect quotes into string

### ISSUE THREAD

**Issue by rodfersou** [plone/plone.recipe.codeanalysis#89]
I have this string in my test case:

        text = '''
        <img src="http://lorempixel.com/400/200/sports/1/" />
        <img src="http://lorempixel.com/400/200/sports/2/" />
        <img src="http://lorempixel.com/400/200/sports/3/" />
        '''

Is it possible to make this option work with it?

**Comment by saily** [comment]
Please open an issue on `flake8-quotes` if this is still an issue, we don't have our own quotes check any more.
