### ISSUE TITLE
jshint does not return error code 1 on warnings

### ISSUE THREAD

**Issue by tisto** [plone/plone.recipe.codeanalysis#94]
I would prefer if the jshint check would return error code 1 on warnings, not only for violations It is confusing if code analysis prints out a warning on travis but does not fail the job.

**Comment by zupo** [comment]
Completely agree on this one.

**Comment by gforcada** [comment]
Isn't there an option on jshint configuration to allow turning warnings into errors? I'm not sold on any side, just wondering...

**Comment by saily** [comment]
@gforcada no there isn't such an option. To avoid breaking a lot of stuff with a new release i'd recommend to add this functionality as an configureable option for `2.0.0` on by default, but ship an upgrade guide how to disable the check similar to:

    [code-analysis]
    recipe = plone.recipe.codeanalysis
    jshint = True
    jshint-bin = ${buildout:bin-directory}/jshint
    jshint-suppress-warnings = True

**Comment by saily** [comment]
@tisto can you please give feedback since you're the author of the ticket.

**Comment by tisto** [comment]
@saily +1 to your proposal.
