### ISSUE TITLE
Sorted imports should be tested for case insensitivity

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.recipe.codeanalysis#97]
We have [evidence that non-case sensitive sorting is better](http://ux.stackexchange.com/a/79266/46964); so, for the sake of our "poor human brains", let's follow plone.api conventions:

https://github.com/plone/plone.api/issues/187

**Comment by hvelarde** [comment]
@saily the tests for imports are not following the [conventions on grouping and sorting](https://github.com/plone/plone.api/blob/1.3.2/docs/contribute/conventions.rst#grouping-and-sorting) after the refactoring:

*So we just sort everything alphabetically and insert one blank line between ``from foo import bar`` and ``import baz`` blocks.*

You are including tests for things like this:

```python
from __future__ import division
from Acquisition import aq_inner
from plone.api import portal
from plone.api.exc import MissingParameterError
from Products.CMFCore.interfaces import ISiteRoot
from Products.CMFCore.WorkflowCore import WorkflowException
import pkg_resources
import random
```

But a typical example should be something like this:

```python
from __future__ import division
from Acquisition import aq_inner
from plone.api import portal
from plone.api.exc import MissingParameterError
from Products.CMFCore.interfaces import ISiteRoot
from Products.CMFCore.WorkflowCore import WorkflowException

import pkg_resources
import random

try:
    pkg_resources.get_distribution('plone.dexterity')
except pkg_resources.DistributionNotFound:
    HAS_DEXTERITY = False
else:
    HAS_DEXTERITY = True
```

**Comment by hvelarde** [comment]
currently this option is useless: https://travis-ci.org/collective/collective.polls/jobs/75008322#L1199

**Comment by saily** [comment]
Go and fix it, you forced the convention-change after i've implemented it aligned to our guidelines.

**Comment by hvelarde** [comment]
sure!

**Comment by hvelarde** [comment]
related with #163

**Comment by do3cc** [comment]
I think this is working already since 2.0
