### ISSUE TITLE
Enforce best practices for testing

### ISSUE THREAD

**Issue by gforcada** [plone/plone.recipe.codeanalysis#98]
Check that all packages have:
- a top-level testing.py module (i.e. plone.api.testing)
- a tests folder
- no references to unittest2 (since plone 4 we advertise that python 2.7 is supported, so bye bye 2.6!)
- no `test_suite` defined on any tests/test_*.py files (as a result of the above)
- the distribution is using its own plone.app.testing layer (not so sure about this one...)
- warnings if the distribution does not depend on plone.app.testing (not so sure about this one either...)
- warning if the distribution _does_ depend on `Products.CMFTestCase`

Any other ideas on the subject?

**Comment by tisto** [comment]
@gforcada +1 in general. not sure if all assumptions are correct (plone.app.testing layer/dependency for instance)

@hvelarde can you elaborate why you need this? Can't you use unittest.skip for that?

**Comment by gforcada** [comment]
@tisto I'm not sure either myself, I was mostly throwing some ideas so that we can decide which ones to incorporate. We should also start small (testing.py, requiring plone.app.testing and tests folder) and once we make all packages follow suit, add more checks.

The up side of this, more than checking for correctness is also a way for new developers to know what is considered best practice. So in a way we could say "Plone best practices? just enable everything on p.r.codeanalysis, that's our best practices".

**Comment by hvelarde** [comment]
@tisto it's perfectly valid to manually define a test suite; in my case I want to skip the whole module in some cases; it's easier to add just a condition in ``test_suite`` that a lot of ``unittest.skipIf`` decorators and using the auto-discovery feature.

but now that you mentioned it, I was checking at the documentation and noticed that the right name to use is ``suite`` or ``load_tests`` so I don't remember where the name ``test_suite`` came from in the first place.

https://docs.python.org/2.7/library/unittest.html#load-tests-protocol

@gforcada :+1: on all you said.

**Comment by aclark4life** [comment]
@hvelarde ``test_suite`` is from setuptools: https://pythonhosted.org/setuptools/setuptools.html#new-and-changed-setup-keywords (I like ``test_suite``)

**Comment by do3cc** [comment]
I Think the CMFTestCase warning is not needed any more. At least not with the newest plone.testing

**Comment by gforcada** [comment]
our template generators are mostly doing that work already, no need to stuff more checks here 😄
